version: '3.4'
services:
  typesense:
    image: typesense/typesense:0.24.1
    container_name: typesense
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://typesense:8108/health | grep -q '\"ok\": true' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
