version: '3.4'
services:
  typesense:
    image: typesense/typesense:27.1
    container_name: typesense
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY:-xyz}
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_ENABLE_CORS=true
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY:-xyz} --enable-cors'
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://typesense:8108/health | grep -q '\"ok\": true' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
